CREATE MEMORY TABLE EXPENSES(
    EXPE_ID BIGINT NOT NULL,
    EXPE_COMM_TX VARCHAR(255),
    EXPE_ITEM_CN DECIMAL(19, 2),
    OPER_DT DATE,
    EXPE_PRIC_AM DECIMAL(19, 2),
    ITEM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);
ALTER TABLE EXPENSES ADD CONSTRAINT EXPENSES_PK PRIMARY KEY(EXPE_ID);
