CREATE MEMORY TABLE FIN_EVENTS(
    EVNT_ID BIGINT NOT NULL,
    EVNT_NAME_TX VARCHAR(255),
    EVNT_DT DATE,
    CPRT_ID BIGINT NOT NULL
);
ALTER TABLE FIN_EVENTS ADD CONSTRAINT FIN_EVENTS_PK PRIMARY KEY(EVNT_ID);
