CREATE MEMORY TABLE INCOMES(
    INCO_ID BIGINT NOT NULL,
    INCO_PRIC_AM DECIMAL(19, 2),
    INCO_COMM_TX VARCHAR(255),
    OPER_DT DATE,
    ITEM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);
ALTER TABLE INCOMES ADD CONSTRAINT INCOMES_PK PRIMARY KEY(INCO_ID);
