CREATE MEMORY TABLE INGREDIENTS(
    INGREDIENT_ID BIGINT NOT NULL,
    INGREDIENT_NAME VARCHAR(255),
    AMOUNT DECIMAL(19, 2),
    RECIPE_ID BIGINT,
    UOM_ID BIGINT
);
ALTER TABLE INGREDIENTS ADD CONSTRAINT INGREDIENTS_PK PRIMARY KEY(INGREDIENT_ID);
