CREATE MEMORY TABLE RECIPES(
    RECIPE_ID BIGINT NOT NULL,
    RECIPE_NAME VARCHAR(255),
    COOK_TIME INTEGER,
    DESCRIPTION VARCHAR(255),
    DIFFICULTY VARCHAR(255),
    DIRECTIONS CLOB,
    IMAGE BLOB,
    PREP_TIME INTEGER,
    SERVINGS INTEGER,
    SOURCE VARCHAR(255),
    TITLE VARCHAR(255),
    URL VARCHAR(255),
    NOTES_ID BIGINT
);
ALTER TABLE RECIPES ADD CONSTRAINT RECIPES_PK PRIMARY KEY(RECIPE_ID);
