CREATE MEMORY TABLE RECIPE_CATEGORY(
    RECIPE_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL
);
ALTER TABLE RECIPE_CATEGORY ADD CONSTRAINT RECIPE_CATEGORY_PK PRIMARY KEY(RECIPE_ID, CATEGORY_ID);
